#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : libkexiv2
Version  : 18.12.3
Release  : 3
URL      : https://download.kde.org/stable/applications/18.12.3/src/libkexiv2-18.12.3.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.3/src/libkexiv2-18.12.3.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.3/src/libkexiv2-18.12.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.0
Requires: libkexiv2-lib = %{version}-%{release}
Requires: libkexiv2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : pkg-config
BuildRequires : pkgconfig(exiv2)
Patch1: 0001-Fix-building-against-exiv2-0.27.patch

%description
EXIV2 Library interface for KDE
-- AUTHORS ------------------------------------------------------------

%package dev
Summary: dev components for the libkexiv2 package.
Group: Development
Requires: libkexiv2-lib = %{version}-%{release}
Provides: libkexiv2-devel = %{version}-%{release}

%description dev
dev components for the libkexiv2 package.


%package lib
Summary: lib components for the libkexiv2 package.
Group: Libraries
Requires: libkexiv2-license = %{version}-%{release}

%description lib
lib components for the libkexiv2 package.


%package license
Summary: license components for the libkexiv2 package.
Group: Default

%description license
license components for the libkexiv2 package.


%prep
%setup -q -n libkexiv2-18.12.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552010518
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1552010518
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libkexiv2
cp COPYING %{buildroot}/usr/share/package-licenses/libkexiv2/COPYING
cp COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/libkexiv2/COPYING-CMAKE-SCRIPTS
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/libkexiv2/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KExiv2/KExiv2/KExiv2
/usr/include/KF5/KExiv2/KExiv2/KExiv2Data
/usr/include/KF5/KExiv2/KExiv2/KExiv2Previews
/usr/include/KF5/KExiv2/KExiv2/RotationMatrix
/usr/include/KF5/KExiv2/kexiv2/kexiv2.h
/usr/include/KF5/KExiv2/kexiv2/kexiv2data.h
/usr/include/KF5/KExiv2/kexiv2/kexiv2previews.h
/usr/include/KF5/KExiv2/kexiv2/libkexiv2_export.h
/usr/include/KF5/KExiv2/kexiv2/rotationmatrix.h
/usr/include/KF5/libkexiv2_version.h
/usr/lib64/cmake/KF5KExiv2/KF5KExiv2Config.cmake
/usr/lib64/cmake/KF5KExiv2/KF5KExiv2ConfigVersion.cmake
/usr/lib64/cmake/KF5KExiv2/KF5KExiv2Targets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5KExiv2/KF5KExiv2Targets.cmake
/usr/lib64/libKF5KExiv2.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5KExiv2.so.15.0.0
/usr/lib64/libKF5KExiv2.so.5.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libkexiv2/COPYING
/usr/share/package-licenses/libkexiv2/COPYING-CMAKE-SCRIPTS
/usr/share/package-licenses/libkexiv2/COPYING.LIB
